flesh out find; consistent options

diff --git a/find b/find
--- a/find
+++ b/find
@@ -3,14 +3,59 @@
 # %helpfile/find [BASE]
 #
 # Find help files (including subtopics) for files starting from BASE or the current directory.  The help files need not be a subdirectory of BASE.
+#
+# Options:
+#     --lang=L      use L instead of $LC_ALL, $LC_CTYPE, or $LANG
+#
+#     --existing    only find help for existing targets
+#     --dirs        only find help for existing directory targets
+#     --files       only find help for existing file targets
+#     --missing     only find help for missing targets
+#
+# -v  --version     version instead of help (--section=version)
+#     --section=S   find section S (default: help)
+#     --debug-locations     show locations on stderr while searching
 
 fatal() {
     printf %s\\n "$(readlink -f "$0") error: $2" >&2
     exit "$1"
 }
 
+section=help
+debug_locations=false
+user_lang=
+user_lang_country=
 handle_option() {
     case "$1" in
+        debug-locations)
+            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
+            debug_locations=true
+            ;;
+        dirs)
+            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
+            fatal 70 TODO
+            ;;
+        existing)
+            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
+            fatal 70 TODO
+            ;;
+        files)
+            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
+            fatal 70 TODO
+            ;;
+        lang)
+            [ $# = 2 ] || fatal 64 "missing value for option $1"
+            user_lang_country="$2"
+            ;;
+        missing)
+            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
+            fatal 70 TODO
+            ;;
+        section)
+            [ $# = 2 ] || fatal 64 "missing value for option $1"
+            [ -n "$2" ] || fatal 64 "empty value for option $1"
+            section="$2"
+            ;;
         *)
             fatal 64 "unknown option: $1"
             ;;
@@ -42,6 +87,38 @@ while [ $# -gt 0 ]; do
             break;;
     esac
 done
+
+check_user_lang_country() {
+    user_lang_country="$(printf %s "${user_lang_country%%.*}" | tr A-Z a-z)"
+    case "$user_lang_country" in
+        [abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz])
+            user_lang="$user_lang_country"
+            user_lang_country=
+            ;;
+        [abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz]_[abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz])
+            user_lang="${user_lang_country%_*}"
+            ;;
+        *)
+            user_lang=
+            user_lang_country=
+            return 1
+            ;;
+    esac
+}
+if [ -n "$user_lang_country" ]; then
+    if [ none = "$user_lang_country" ]; then
+        user_lang=
+        user_lang_country=
+    else
+        check_user_lang_country || fatal 64 'invalid --lang value'
+    fi
+else
+    for user_lang_country in "${LC_ALL:-}" "${LC_CTYPE:-}" "${LANG:-}"; do
+        if check_user_lang_country; then
+            break
+        fi
+    done
+fi
 
 
 if [ $# -gt 1 ]; then
diff --git a/locate b/locate
--- a/locate
+++ b/locate
@@ -7,13 +7,14 @@
 # Output on success is "file FILENAME", "internal SECTION FILENAME", or "man SECTION NAME".
 #
 # Options:
-# -v  --version     version instead of help
+# -v  --version     version instead of help (--section=version)
 #     --lang=L      use L instead of $LC_ALL, $LC_CTYPE, or $LANG
 #     --format=F    preferred formats, comma separated
 # -a  --all         list all matches instead of first
 #
 # -c  --command     lookup through $PATH if NAME lacks "/", like which(1)
 #
+#     --section=S   locate section S (default: help)
 #     --debug-locations     show locations on stderr while searching
 
 fatal() {
@@ -22,6 +23,7 @@ fatal() {
 }
 
 section=help
+user_lang=
 user_lang_country=
 first_lang_file=
 pref_formats=
@@ -44,7 +46,7 @@ handle_option() {
             debug_locations=true
             ;;
         format)
-            [ $# = 2 ] || fatal 64 "expected value for option $1"
+            [ $# = 2 ] || fatal 64 "missing value for option $1"
             x="$(printf %s "$2" | LC_ALL=C tr -d -c \\-A-Za-z0-9.,_)"
             if [ x"$x" != x"$2" ]; then
                 fatal 64 'invalid --format value'
@@ -52,8 +54,13 @@ handle_option() {
             pref_formats="$(printf %s "$2" | tr , ' ')"
             ;;
         lang)
-            [ $# = 2 ] || fatal 64 "expected value for option $1"
+            [ $# = 2 ] || fatal 64 "missing value for option $1"
             user_lang_country="$2"
+            ;;
+        section)
+            [ $# = 2 ] || fatal 64 "missing value for option $1"
+            [ -n "$2" ] || fatal 64 "empty value for option $1"
+            section="$2"
             ;;
         v|version)
             [ $# = 1 ] || fatal 64 "unexpected value for option $1"
